apiVersion: v1
kind: Service
metadata:
  name: nginx-test-nodeport
  namespace: edu-focused-lamarr
spec:
  type: NodePort
  selector:
    Lesson: kubernetes_2
    branch: k8s-Lesson2
    owner: jmuriki
    env: dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30021
