apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-test-pod
  namespace: edu-focused-lamarr
  labels:
    Lesson: kubernetes_2
    branch: k8s-Lesson2
    owner: jmuriki
    env: dev
spec:
  containers:
    - name: ubuntu-test-container
      image: ubuntu:latest
      command: ["sleep", "infinity"]
