apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-test-django-clearsessions-cronjob
  labels:
    Lesson: minikube_1
    env: prod
    owner: jmuriki
spec:
  schedule: "0 0 * * * "
  startingDeadlineSeconds: 10
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 1
      template:
        metadata:
          labels:
            app: k8s-test-django-clearsessions-cronjob
        spec:
          containers:
            - name: k8s-test-django-container
              image: k8s-test_django_app
              command:
                - python
                - manage.py
                - clearsessions
              envFrom:
                - secretRef:
                    name: k8s-test-django-secrets-prod
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
